project_id = "hnobiejtlcutayoiqvov"

[functions.chat]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false
